<?xml version="1.0" encoding="utf-8"?>
<script src="http://ossweb-img.qq.com/images/js/eas/eas.js?v=3_8_8_2016_15_4_final_3"></script>
<script>
	if(typeof(EAS.Init) == 'function'){EAS.Init();};
</script>
<!--footer s-->
<div class="footer">
	<div class="f_con">
		<a class="f_con_logo target-blank" href="http://game.qq.com/index.shtml" target="_blank">腾讯互动娱乐</a>
		<a class="f_con_logo1 target-blank" href="http://www.horizon3d.com.cn" target="_blank">永航科技</a>
		<p>
			<a class="target-blank" href="http://game.qq.com/portal2010/about.htm" target="_blank" title="腾讯互动娱乐">腾讯互动娱乐</a>   |
			<a class="target-blank" href="http://game.qq.com/contract.shtml" target="_blank" title="服务条款">服务条款</a>   |
			<!--a class="target-blank" href="http://adver.qq.com/" target="_blank" title="广告服务">广告服务</a>   |-->
			<a class="target-blank" href="http://game.qq.com/hr/" target="_blank" title="腾讯游戏招聘">腾讯游戏招聘</a>   |
			<a class="target-blank" href="http://service.qq.com/" target="_blank" title="腾讯游戏客服">腾讯游戏客服</a>   |
			<a class="target-blank" href="http://game.qq.com/gnav/" target="_blank" title="游戏地图">游戏地图</a>   |
			<a class="target-blank" href="http://tgact.qq.com/?g=x5" target="_blank" title="游戏活动">游戏活动</a>   |
			<!--a class="target-blank" href="http://game.qq.com/new05/act/hezuo.shtml" target="_blank" title="商务合作">商务合作</a>   |-->
			<a class="target-blank" href="http://www.qq.com/map/" target="_blank" title="网站导航">网站导航</a><br/>
			<a class="target-blank" href="javascript:;" style="cursor:default;">网络文化经营许可证：粤网文[2014]0633-233号</a>   |
			<a class="target-blank" href="javascript:;" style="cursor:default;">文网备字（2009）43号</a>   |
			<a class="target-blank" href="javascript:;" style="cursor:default;">新出网证（粤）字010号</a></br>
			<a class="target-blank" href="javascript:;" style="cursor:default;">批准文号：京新出音[2008]249号</a>   |
			<a class="target-blank" href="javascript:;" style="cursor:default;">出版物号：978-7-900179-43-2</a>
            <span style="cursor:default;">本网络游戏适合年满14岁以上的用户使用；请您确定已如实进行实名注册；为了您的健康，请合理控制游戏时间。</span>
			<span style="cursor:default;">COPYRIGHT © 1998 - 2017 TENCENT. ALL RIGHTS RESERVED. 腾讯公司 版权所有</span>
		</p>
	</div>
  <span id="mgc-debugger-btn"></span>
  <div id="mgc-debugger-panl">
    <textarea id="mgc-debugger-area"></textarea>
    <textarea id="mgc-debugger-txt" placeholder="console.log('... ')"></textarea>
    <a id="mgc-debugger-submit" href="javascript:;">执行</a>
  </div>
</div>
<!--footer e-->