<?xml version="1.0" encoding="utf-8"?>
<ul class="sd_quick">
  <li>
    <a class="top" href="javascript:mgc.tools.EAS([{'e_c': 'mgc.uptotop','c_t':4}]);">回顶</a>
  </li>
  <li style="display:none;" >
    <a class="help target-blank" onclick="mgc.tools.EAS([{'e_c': 'mgc.help','c_t':4}]);" target="_blank"  href="http://mgc.qq.com/help/index.shtml">帮助</a>
  </li>
  <li style="display:none;" >
    <a class="feedback target-blank" onclick="mgc.tools.EAS([{'e_c': 'mgc.feedback','c_t':4}])" target="_blank" href="http://x5.gamebbs.qq.com/forum.php?mod=viewthread&tid=1671176&extra=page%3D1">反馈</a>
  </li>
  <li>
    <a class="slideToggle _slideToggle" href="javascript:;">展开</a>
  </li>
</ul>
<!--<script src="js/mgc_susnav.js?v=3_8_8_2016_15_4_final_3" defer="defer"></script>-->
