<?xml version="1.0" encoding="utf-8"?>
<!--梦工厂贵族 -->
<div class="pop pop_mgc" id="mgc_vip">
  <a href="javascript:showDialog.hide();" class="pop_close">关闭</a>
  <p class="pop_title">梦工厂贵族</p>
  <p class="tit_mgc_status">
    您的身份：<label id="myDegree">无</label>
  </p>
  <div class="bd">
    <div class="tit_mgc">
      <b>贵族特权</b>
      <i class="line"></i>
      <p class="f_right">
        <a class="knowmore target-blank" href="http://x5.qq.com/act/a20140428may/page03.htm#0" target="_blank">
          更多<i></i>
        </a>
        <a class="pop_btn pop_btn_pay" onclick="mgc.tools.EAS([{'e_c': 'mgc.charge','c_t':4}])" href="http://pay.qq.com/ipay/index.shtml?c=qxwwqp" target="_blank">充值</a>
      </p>
    </div>
    <div class="pop_table">
      <ul class="clearfix" id="open_vip_list">
        <li class="pt_title">
          <div>
            <b class="p_empty"></b>
            <b>特殊标识</b>
            <b>玩家列表字体</b>
            <b>免费飞屏喇叭</b>
            <b>人满房间特权</b>
            <b>抢座免费特权</b>
            <b>抢座增加热度值</b>
            <b>房间热度加成</b>
            <b>飞屏喇叭效果</b>
            <b>防止守护禁言</b>
            <b>每日工资加成</b>
            <b>礼物红包效果</b>
            <b>隐身功能</b>
            <b>返利炫豆比例</b>
          </div>
        </li>
        <li>
          <a class="vip-1" href="javascript:;" vip="1">
            <b class="p_bold">近卫</b>
            <b>
              <span class="b_icon_honor b_icon_honor1"></span>
            </b>
            <b>
              <img class="font" width="70" height="20" alt="字体效果" src="http://ossweb-img.qq.com/images/mgc/css_img/vip_panel/font_style1.png?v=3_8_8_2016_15_4_final_3"/>
            </b>
            <b>
              每天<span class="p_red">1</span>个
            </b>
            <b>
              <span class="p_red">1</span>次/天，低优先级
            </b>
            <b>每天1次</b>
            <b>有</b>
            <b>无</b>
            <b>
              <img width="80" height="37" alt="飞屏喇叭效果" src="http://ossweb-img.qq.com/images/mgc/css_img/vip_panel/laba1.png?v=3_8_8_2016_15_4_final_3"/>
            </b>
            <b>无</b>
            <b>10%</b>
            <b>无</b>
            <b>无</b>
            <b class="rebate_num">-</b>
          </a>
        </li>
        <li>
          <a class="vip-2" href="javascript:;" vip="2">
            <b class="p_bold">骑士</b>
            <b>
              <span class="b_icon_honor b_icon_honor2"></span>
            </b>
            <b>
              <img class="font" width="70" height="20" alt="字体效果" src="http://ossweb-img.qq.com/images/mgc/css_img/vip_panel/font_style2.png?v=3_8_8_2016_15_4_final_3"/>
            </b>
            <b>
              每天<span class="p_red">2</span>个
            </b>
            <b>
              <span class="p_red">3</span>次/天，低优先级
            </b>
            <b>每天2次</b>
            <b>有</b>
            <b>无</b>
            <b>
              <img width="80" height="37" alt="飞屏喇叭效果" src="http://ossweb-img.qq.com/images/mgc/css_img/vip_panel/laba2.png?v=3_8_8_2016_15_4_final_3"/>
            </b>
            <b>无</b>
            <b>20%</b>
            <b>无</b>
            <b>无</b>
            <b class="rebate_num">-</b>
          </a>
        </li>
        <li>
          <a class="vip-3" href="javascript:;" vip="3">
            <b class="p_bold">将军</b>
            <b>
              <span class="b_icon_honor b_icon_honor3"></span>
            </b>
            <b>
              <img class="font" width="70" height="20" alt="字体效果" src="http://ossweb-img.qq.com/images/mgc/css_img/vip_panel/font_style3.png?v=3_8_8_2016_15_4_final_3"/>
            </b>
            <b>
              每天<span class="p_red">5</span>个
            </b>
            <b>
              <span class="p_red">无限</span>次数，<span class="p_red">中级</span>优先
            </b>
            <b>每天3次</b>
            <b>有</b>
            <b>无</b>
            <b>
              <img width="80" height="37" alt="飞屏喇叭效果" src="http://ossweb-img.qq.com/images/mgc/css_img/vip_panel/laba3.png?v=3_8_8_2016_15_4_final_3"/>
            </b>
            <b>天使守护或以下</b>
            <b>50%</b>
            <b>无</b>
            <b>有</b>
            <b class="rebate_num">-</b>
          </a>
        </li>
        <li>
          <a class="vip-4" href="javascript:;" vip="4">
            <b class="p_bold">亲王</b>
            <b>
              <span class="b_icon_honor b_icon_honor4"></span>
            </b>
            <b>
              <img class="font" width="70" height="20" alt="字体效果" src="http://ossweb-img.qq.com/images/mgc/css_img/vip_panel/font_style4.png?v=3_8_8_2016_15_4_final_3"/>
            </b>
            <b>
              每天<span class="p_red">10</span>个
            </b>
            <b>
              <span class="p_red">无限</span>次数，<span class="p_red">高级</span>优先
            </b>
            <b>每天4次</b>
            <b>有</b>
            <b>50热度/分钟</b>
            <b>
              <img width="80" height="37" alt="飞屏喇叭效果" src="http://ossweb-img.qq.com/images/mgc/css_img/vip_panel/laba4.png?v=3_8_8_2016_15_4_final_3"/>
            </b>
            <b>至尊守护或以下</b>
            <b>100%</b>
            <b>有</b>
            <b>有</b>
            <b class="rebate_num">-</b>
          </a>
        </li>
        <li>
          <a class="vip-5" href="javascript:;" vip="5">
            <b class="p_bold">皇帝</b>
            <b>
              <span class="b_icon_honor b_icon_honor5"></span>
            </b>
            <b>
              <img class="font" width="70" height="20" alt="字体效果" src="http://ossweb-img.qq.com/images/mgc/css_img/vip_panel/font_style5.png?v=3_8_8_2016_15_4_final_3"/>
            </b>
            <b>
              每天<span class="p_red">30</span>个
            </b>
            <b>
              <span class="p_red">无限</span>次数，<span class="p_blue">最高</span>优先
            </b>
            <b>每天5次</b>
            <b>有</b>
            <b>100热度/分钟</b>
            <b>
              <img width="80" height="37" alt="飞屏喇叭效果" src="http://ossweb-img.qq.com/images/mgc/css_img/vip_panel/laba5.png?v=3_8_8_2016_15_4_final_3"/>
            </b>
            <b>超凡守护或以下</b>
            <b>200%</b>
            <b>有</b>
            <b>有</b>
            <b class="rebate_num">-</b>
          </a>
        </li>
      </ul>
    </div>
    <div class="pop_mgc_list clearfix">
      <p class="pop_t_txt">开通时间：</p>
      <div class="pop_open">
        <div class="select_box">
          <div id="select_open_btn" class="select_input select_input1">
            <span>
              近卫(30天)  5000<i class="icon_mhb"></i>
            </span>
          </div>
          <ul id="select_open_list" class="select_more">
          </ul>
        </div>
      </div>
      <p class="pop_t_txt">付费方式：</p>
      <div class="pop_open">
        <div class="select_box">
          <div id="select_pay_btn" class="select_input select_input2">
            <span>
              炫豆<i class="icon_mhb"></i>
            </span>
          </div>
          <ul id="select_pay_list" class="select_more select_more2">
          </ul>
        </div>
      </div>
      <p class="pop_t_txt pop_t_txt_no">（不返利）</p>
    </div>
  </div>
  <p class="pop_mgc_tips">如果开通新的贵族身份，您身上原有的贵族身份会被系统直接收回。开通贵族后，使用续费功能延期会有折扣哦~</p>
  <div class="pop_btn_box clearfix">
    <a class="btn_disabled" href="javascript:;" id="ktBtn">开通</a>
    <a class="btn_disabled" href="javascript:;" id="xfBtn">续费</a>
  </div>
  <div class="mhb_tips_vip">
    梦幻币<br />通过签到、任务、等级成长等方式获得，可用来购买梦幻币礼物及贵族身份。
  </div>
  <div class="xd_tips_vip">
    炫豆<br />通过充值获得，可用来购买付费礼物、贵族身份等，消费炫豆还能够增加财富值哦！
  </div>
  <div class="mhb_tips_vip_2">
    梦幻币<br />通过签到、任务、等级成长等方式获得，可用来购买梦幻币礼物及贵族身份。
  </div>
  <div class="xd_tips_vip_2">
    炫豆<br />通过充值获得，可用来购买付费礼物、贵族身份等，消费炫豆还能够增加财富值哦！
  </div>
</div>
